### ISSUE TITLE
question: Application expected to open port < 1024?

### ISSUE THREAD

**Issue by duesee** [pimalaya/ortie#1]
When I run ...

```sh
$ cargo run -- auth get
```

... I get ...

```sh
Created authorization request with:
 - state: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Sending authorization request to your browser…
Spawn fake HTTP redirection server…
Error: Permission denied (os error 13)
```

Out of curiosity, I gave the application the capability to open ports < 1024 with ...

```sh
sudo setcap 'cap_net_bind_service=+ep' ./target/debug/ortie
```

... and this seems to resolve the permission issue. However with Google and Thunderbird App-ID I still get in a browser ...

```
Access blocked: Authorization Error
Missing required parameter: redirect_uri [Learn more about this error](https://developers.google.com/identity/protocols/oauth2)
If you are a developer of Mozilla Thunderbird Email, see [error details](https://accounts.google.com/).
Error 400: invalid_request
```

Thank you for initiating this project!

My config:

```toml
# The account name should be unique.
#
[accounts.poddebniak]

# Make this current account the default one to use when no account is
# specified in the CLI with the --account argument.
#
default = true

# The client credentials
#
client-id = "406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com"
client-secret.raw = "kSmqreRr0qwBWJgbf5Y-PjSU"
#client-secret.command = "pass show example"
#client-secret.keyring = "example"

# Endpoints, given by your OAuth provider.
#
endpoints.authorization = "https://accounts.google.com/o/oauth2/auth"
endpoints.token = "https://www.googleapis.com/oauth2/v3/token"
#endpoints.redirection = "http://localhost"

# Access token scopes
#
scopes = []

# TLS configuration
#
#tls = "native-tls"
#tls = "rustls-aws"
#tls = "rustls-ring"

# Enables Proof Key for Code Exchange (rfc7636)
#
pkce = false

# Automatically refreshes expired access token when using `ortie token
# show` command.
#
auto-refresh = false

# Access token storage
#
storage.read.command = ["pass", "show", "ortie/example"]
storage.write.command = ["pass", "insert", "-e", "ortie/example"]
#storage.read.keyring = "ortie-example"
#storage.write.keyring = "ortie-example"

# Hooks
#
#on-issue-access-token.success.command = []
#on-issue-access-token.success.notify.summary = "Ortie"
#on-issue-access-token.success.notify.body = "Issued access token (expires in $EXPIRES_IN)"
#
#on-issue-access-token.error.command = []
#on-issue-access-token.error.notify.summary = "Ortie"
#on-issue-access-token.error.notify.body = "[$ERROR] Issue access token error\n$ERROR_DESCRIPTION"
#
#on-refresh-access-token.success.command = []
#on-refresh-access-token.success.notify.summary = "Ortie"
#on-refresh-access-token.success.notify.body = "Refreshed access token (expires in $EXPIRES_IN)"
#
#on-refresh-access-token.error.command = []
#on-refresh-access-token.error.notify.summary = "Ortie"
#on-refresh-access-token.error.notify.body = "[$ERROR] Refresh access token error\n$ERROR_DESCRIPTION"
```
